name: checking working directory
on : [push]
jobs:
    checke_working_directory:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: |
                 pwd
                 ls -l
                 echo "::warning:: this is warning message"
    display_variables:
        runs-on: ubuntu-latest
        needs: checke_working_directory
        steps:
            - name: desplay variables
              run: echo $GITHUB_REPOSITORY
               
