name: checkout
on: [push]
jobs:
    test-job:
      runs-on: ubuntu-latest
      steps:
        - name: ls
          run: ls -al
        - uses: actions/checkout@v3
        - name: ls2
          run: ls -al
